name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run test:e2e
      - name: Store artifacts
        uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: cypress-screenshots
            path: cypress/screenshots
            name: cypress-videos
            path: cypress/videos